/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Canonical OpenFGA Administration Product Compatibility API
 * The following specification outlines the API required for the FGA administration frontend to interact with an OpenFGA instance through a products API. This is an evolving specification as reflected in the version number.

#### Changelog
| Version | Notes |
|---|---|
| **0.0.6** | Ensured compatibility with Orval Restful Client Generator. |
| **0.0.5** | Add filter parameter to top level collection `GET` requests. |
| **0.0.4** | Added pagination parameters to appropriate `GET` requests.<br />Changed a couple of `PUT`'s to `PATCH`'s to account for the possible subset returned from the paginated `GET`'s. |
| **0.0.3** | Added skeleton error responses for `400`, `401`, `404`, and `5XX` (`default`) |
| **0.0.2** | Added `GET /users/{id}/groups`<br />Added `GET /users/{id}roles`<br />Added `GET /users/{id}/entitlements`<br />Added `GET,PUT /groups/{id}/users`<br>Added `DELETE /groups/{id}/users/{userId}`<br />Added `GET /roles/{id}/entitlements`<br />Added `DELETE /roles/{id}/entitlements/{entitlementId}` |
| **0.0.1** | Initial dump |

 * OpenAPI spec version: 0.0.6
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse, AxiosError } from "axios";
import { useQuery, useMutation } from "@tanstack/react-query";
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey,
} from "@tanstack/react-query";
import type {
  GetEntitlements200OneItem,
  BadRequestResponse,
  UnauthorizedResponse,
  NotFoundResponse,
  DefaultResponse,
  GetEntitlementsParams,
} from "../api.schemas";

/**
 * The text/plain response type will return the raw authorisation model.
 * @summary Get the list of entitlements.
 */
export const getEntitlements = (
  params?: GetEntitlementsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetEntitlements200OneItem[] | string>> => {
  return axios.default.get(`/entitlements`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetEntitlementsQueryKey = (params?: GetEntitlementsParams) => {
  return [`/entitlements`, ...(params ? [params] : [])] as const;
};

export const getGetEntitlementsQueryOptions = <
  TData = Awaited<ReturnType<typeof getEntitlements>>,
  TError = AxiosError<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
>(
  params?: GetEntitlementsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getEntitlements>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEntitlementsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntitlements>>> = ({
    signal,
  }) => getEntitlements(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEntitlements>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetEntitlementsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEntitlements>>
>;
export type GetEntitlementsQueryError = AxiosError<
  BadRequestResponse | UnauthorizedResponse | NotFoundResponse | DefaultResponse
>;

/**
 * @summary Get the list of entitlements.
 */
export const useGetEntitlements = <
  TData = Awaited<ReturnType<typeof getEntitlements>>,
  TError = AxiosError<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
>(
  params?: GetEntitlementsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getEntitlements>>,
      TError,
      TData
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetEntitlementsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Update the authorisation model.
 */
export const putEntitlements = (
  putEntitlementsBody: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<string>> => {
  return axios.default.put(`/entitlements`, putEntitlementsBody, options);
};

export const getPutEntitlementsMutationOptions = <
  TError = AxiosError<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putEntitlements>>,
    TError,
    { data: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putEntitlements>>,
  TError,
  { data: string },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putEntitlements>>,
    { data: string }
  > = (props) => {
    const { data } = props ?? {};

    return putEntitlements(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutEntitlementsMutationResult = NonNullable<
  Awaited<ReturnType<typeof putEntitlements>>
>;
export type PutEntitlementsMutationBody = string;
export type PutEntitlementsMutationError = AxiosError<
  BadRequestResponse | UnauthorizedResponse | NotFoundResponse | DefaultResponse
>;

/**
 * @summary Update the authorisation model.
 */
export const usePutEntitlements = <
  TError = AxiosError<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putEntitlements>>,
    TError,
    { data: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getPutEntitlementsMutationOptions(options);

  return useMutation(mutationOptions);
};
