/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Canonical OpenFGA Administration Product Compatibility API
 * The following specification outlines the API required for the FGA administration frontend to interact with an OpenFGA instance through a products API. This is an evolving specification as reflected in the version number.

 * OpenAPI spec version: 0.0.10
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../api-utils/mutator/custom-instance";
import type { ErrorType } from "../../api-utils/mutator/custom-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * This endpoint returns the implemented OpenAPI spec, which could be used for debugging, browsing, API discovery, etc.
 * @summary Returns the OpenAPI spec as a JSON file.
 */
export const swaggerJson = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<string>(
    { url: `/swagger.json`, method: "GET", signal },
    options,
  );
};

export const getSwaggerJsonQueryKey = () => {
  return [`/swagger.json`] as const;
};

export const getSwaggerJsonQueryOptions = <
  TData = Awaited<ReturnType<typeof swaggerJson>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof swaggerJson>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSwaggerJsonQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof swaggerJson>>> = ({
    signal,
  }) => swaggerJson(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof swaggerJson>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SwaggerJsonQueryResult = NonNullable<
  Awaited<ReturnType<typeof swaggerJson>>
>;
export type SwaggerJsonQueryError = ErrorType<unknown>;

/**
 * @summary Returns the OpenAPI spec as a JSON file.
 */
export const useSwaggerJson = <
  TData = Awaited<ReturnType<typeof swaggerJson>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof swaggerJson>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getSwaggerJsonQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
