/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Canonical OpenFGA Administration Product Compatibility API
 * The following specification outlines the API required for the FGA administration frontend to interact with an OpenFGA instance through a products API. This is an evolving specification as reflected in the version number.

 * OpenAPI spec version: 0.0.10
 */
import { faker } from "@faker-js/faker";
import { HttpResponse, delay, http } from "msw";

import type {
  GetAuthenticationProviders200,
  GetIdentityProvidersResponse,
  IdentityProvider,
} from "../api.schemas";

export const getGetAuthenticationProvidersResponseMock = (
  overrideResponse: any = {},
): GetAuthenticationProviders200 => ({
  _links: {
    next: { href: faker.word.sample(), ...overrideResponse },
    ...overrideResponse,
  },
  _meta: {
    page: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    pageToken: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    size: faker.number.int({ min: undefined, max: undefined }),
    total: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    ...overrideResponse,
  },
  message: faker.word.sample(),
  status: faker.number.int({ min: undefined, max: undefined }),
  ...overrideResponse,
  data: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({})),
  ...overrideResponse,
});

export const getGetAuthenticationResponseMock = (
  overrideResponse: any = {},
): GetIdentityProvidersResponse => ({
  _links: {
    next: { href: faker.word.sample(), ...overrideResponse },
    ...overrideResponse,
  },
  _meta: {
    page: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    pageToken: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    size: faker.number.int({ min: undefined, max: undefined }),
    total: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    ...overrideResponse,
  },
  message: faker.word.sample(),
  status: faker.number.int({ min: undefined, max: undefined }),
  ...overrideResponse,
  data: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.word.sample(),
    name: faker.word.sample(),
    ...overrideResponse,
  })),
  ...overrideResponse,
});

export const getPostAuthenticationResponseMock = (
  overrideResponse: any = {},
): IdentityProvider => ({
  acceptsPromptNone: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  accountLinkingOnly: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  clientID: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  clientSecret: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  disableIdentityInfo: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  enabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  id: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  identityCount: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  redirectUrl: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  storeTokens: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  storeTokensReadable: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  syncMode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["import"] as const),
    undefined,
  ]),
  trustEmail: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getGetAuthenticationItemResponseMock = (
  overrideResponse: any = {},
): IdentityProvider => ({
  acceptsPromptNone: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  accountLinkingOnly: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  clientID: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  clientSecret: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  disableIdentityInfo: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  enabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  id: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  identityCount: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  redirectUrl: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  storeTokens: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  storeTokensReadable: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  syncMode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["import"] as const),
    undefined,
  ]),
  trustEmail: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  ...overrideResponse,
});

export const getGetAuthenticationProvidersMockHandler = (
  overrideResponse?: GetAuthenticationProviders200,
) => {
  return http.get("*/authentication/providers", async () => {
    await delay(1000);
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getGetAuthenticationProvidersResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    );
  });
};

export const getGetAuthenticationMockHandler = (
  overrideResponse?: GetIdentityProvidersResponse,
) => {
  return http.get("*/authentication", async () => {
    await delay(1000);
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getGetAuthenticationResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    );
  });
};

export const getPostAuthenticationMockHandler = (
  overrideResponse?: IdentityProvider,
) => {
  return http.post("*/authentication", async () => {
    await delay(1000);
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getPostAuthenticationResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    );
  });
};

export const getGetAuthenticationItemMockHandler = (
  overrideResponse?: IdentityProvider,
) => {
  return http.get("*/authentication/:id", async () => {
    await delay(1000);
    return new HttpResponse(
      JSON.stringify(
        overrideResponse
          ? overrideResponse
          : getGetAuthenticationItemResponseMock(),
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      },
    );
  });
};

export const getPutAuthenticationItemMockHandler = () => {
  return http.put("*/authentication/:id", async () => {
    await delay(1000);
    return new HttpResponse(null, {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    });
  });
};

export const getDeleteAuthenticationItemMockHandler = () => {
  return http.delete("*/authentication/:id", async () => {
    await delay(1000);
    return new HttpResponse(null, {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    });
  });
};
export const getAuthenticationMock = () => [
  getGetAuthenticationProvidersMockHandler(),
  getGetAuthenticationMockHandler(),
  getPostAuthenticationMockHandler(),
  getGetAuthenticationItemMockHandler(),
  getPutAuthenticationItemMockHandler(),
  getDeleteAuthenticationItemMockHandler(),
];
