/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Canonical OpenFGA Administration Product Compatibility API
 * The following specification outlines the API required for the FGA administration frontend to interact with an OpenFGA instance through a products API. This is an evolving specification as reflected in the version number.

#### Changelog
| Version | Notes |
|---|---|
| **0.0.8** | Implement response type as defined in [IAM Platform Admin UI HTTP Spec](https://docs.google.com/document/d/1ElV22e3mePGFPq8CaM3F3IkuyuOLNpjG7yYgtjvygf4/edit). |
| **0.0.7** | Added `/entitlements/raw` endpoint to split `/entitlements` responses. |
| **0.0.6** | Ensured compatibility with Orval Restful Client Generator. |
| **0.0.5** | Add filter parameter to top level collection `GET` requests. |
| **0.0.4** | Added pagination parameters to appropriate `GET` requests.<br />Changed a couple of `PUT`'s to `PATCH`'s to account for the possible subset returned from the paginated `GET`'s. |
| **0.0.3** | Added skeleton error responses for `400`, `401`, `404`, and `5XX` (`default`) |
| **0.0.2** | Added `GET /users/{id}/groups`<br />Added `GET /users/{id}roles`<br />Added `GET /users/{id}/entitlements`<br />Added `GET,PUT /groups/{id}/users`<br>Added `DELETE /groups/{id}/users/{userId}`<br />Added `GET /roles/{id}/entitlements`<br />Added `DELETE /roles/{id}/entitlements/{entitlementId}` |
| **0.0.1** | Initial dump |

 * OpenAPI spec version: 0.0.8
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../api-utils/mutator/custom-instance";
import type { ErrorType } from "../../api-utils/mutator/custom-instance";
import type {
  BadRequestResponse,
  DefaultResponse,
  GetAuthentication200,
  GetAuthenticationParams,
  GetAuthenticationProvidersParams,
  IdentityProvider,
  NotFoundResponse,
  Response,
  UnauthorizedResponse,
} from "../api.schemas";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Returns the list of supported identity providers.
 */
export const getAuthenticationProviders = (
  params?: GetAuthenticationProvidersParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Response>(
    { url: `/authentication/providers`, method: "GET", params, signal },
    options,
  );
};

export const getGetAuthenticationProvidersQueryKey = (
  params?: GetAuthenticationProvidersParams,
) => {
  return [`/authentication/providers`, ...(params ? [params] : [])] as const;
};

export const getGetAuthenticationProvidersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthenticationProviders>>,
  TError = ErrorType<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
>(
  params?: GetAuthenticationProvidersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuthenticationProviders>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthenticationProvidersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAuthenticationProviders>>
  > = ({ signal }) =>
    getAuthenticationProviders(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthenticationProviders>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuthenticationProvidersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthenticationProviders>>
>;
export type GetAuthenticationProvidersQueryError = ErrorType<
  BadRequestResponse | UnauthorizedResponse | NotFoundResponse | DefaultResponse
>;

/**
 * @summary Returns the list of supported identity providers.
 */
export const useGetAuthenticationProviders = <
  TData = Awaited<ReturnType<typeof getAuthenticationProviders>>,
  TError = ErrorType<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
>(
  params?: GetAuthenticationProvidersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuthenticationProviders>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuthenticationProvidersQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary List authentication methods.
 */
export const getAuthentication = (
  params?: GetAuthenticationParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetAuthentication200>(
    { url: `/authentication`, method: "GET", params, signal },
    options,
  );
};

export const getGetAuthenticationQueryKey = (
  params?: GetAuthenticationParams,
) => {
  return [`/authentication`, ...(params ? [params] : [])] as const;
};

export const getGetAuthenticationQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthentication>>,
  TError = ErrorType<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
>(
  params?: GetAuthenticationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuthentication>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthenticationQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAuthentication>>
  > = ({ signal }) => getAuthentication(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthentication>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuthenticationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthentication>>
>;
export type GetAuthenticationQueryError = ErrorType<
  BadRequestResponse | UnauthorizedResponse | NotFoundResponse | DefaultResponse
>;

/**
 * @summary List authentication methods.
 */
export const useGetAuthentication = <
  TData = Awaited<ReturnType<typeof getAuthentication>>,
  TError = ErrorType<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
>(
  params?: GetAuthenticationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuthentication>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuthenticationQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Register a new authentication method.
 */
export const postAuthentication = (
  identityProvider: IdentityProvider,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<IdentityProvider>(
    {
      url: `/authentication`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: identityProvider,
    },
    options,
  );
};

export const getPostAuthenticationMutationOptions = <
  TError = ErrorType<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthentication>>,
    TError,
    { data: IdentityProvider },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthentication>>,
  TError,
  { data: IdentityProvider },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthentication>>,
    { data: IdentityProvider }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthentication(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthenticationMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthentication>>
>;
export type PostAuthenticationMutationBody = IdentityProvider;
export type PostAuthenticationMutationError = ErrorType<
  BadRequestResponse | UnauthorizedResponse | NotFoundResponse | DefaultResponse
>;

/**
 * @summary Register a new authentication method.
 */
export const usePostAuthentication = <
  TError = ErrorType<
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | DefaultResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthentication>>,
    TError,
    { data: IdentityProvider },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthentication>>,
  TError,
  { data: IdentityProvider },
  TContext
> => {
  const mutationOptions = getPostAuthenticationMutationOptions(options);

  return useMutation(mutationOptions);
};
