export enum Endpoint {
  AUTHENTICATION = "/authentication",
  AUTHENTICATION_PROVIDER = "/authentication/{id}",
  AUTHENTICATION_PROVIDERS = "/authentication/providers",
  CAPABILITIES = "/capabilities",
  ENTITLEMENTS = "/entitlements",
  ENTITLEMENTS_RAW = "/entitlements/raw",
  GROUP = "/groups/{id}",
  GROUP_ENTITLEMENTS = "/groups/{id}/entitlements",
  GROUP_IDENTITIES = "/groups/{id}/identities",
  GROUP_ROLES = "/groups/{id}/roles",
  GROUPS = "/groups",
  IDENTITIES = "/identities",
  IDENTITY = "/identities/{id}",
  IDENTITY_ENTITLEMENTS = "/identities/{id}/entitlements",
  IDENTITY_GROUPS = "/identities/{id}/groups",
  IDENTITY_ROLES = "/identities/{id}/roles",
  META = "/swagger.json",
  RESOURCES = "/resources",
  ROLE = "/roles/{id}",
  ROLE_ENTITLEMENTS = "/roles/{id}/entitlements",
  ROLES = "/roles",
}
