name: Upload TICS report
on:
  push:
    branches:
      - main

jobs:
  TICS:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install
        run: yarn install --immutable
      - run: yarn test --coverage.enabled true
      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v2
        with:
          projectName: rebac-admin
          ticsConfiguration: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true